### ISSUE TITLE
Incease the cotrast for left panel toggle

### ISSUE THREAD

**Issue by Gisonrg** [Connectr-CS3216/Connectr-Frontend#3]
The current color is quite dark and it is similar to the background, making it very hard to see

**Comment by fischsux** [comment]
This design decision is made purposely to avoid interfering users' normal interaction. We can make the panel out on default to suggest users its availability

**Comment by Gisonrg** [comment]
@null09264 
That make sense, but make sure use some highlights to make sure our users notice it for the very first time.
